TRUNCATE TABLE account_users RESTART IDENTITY CASCADE;
TRUNCATE TABLE user_audit RESTART IDENTITY CASCADE;
TRUNCATE TABLE account_audit RESTART IDENTITY CASCADE;
TRUNCATE TABLE accounts RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;
